name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
          # Install your requirements (excluding heavy GPU libs for testing speed)
          # We manually install CPU versions of torch for testing to be fast
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install fastapi uvicorn pydantic transformers peft
          
      - name: Run Tests
        run: |
          # Run the tests we created in Step A
          pytest tests/
          
  sync-to-hub:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() # Only run if tests passed
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: pierreramez 
          SPACE_NAME: chatbot-api
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Add Hugging Face as a remote
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          
          # Force push to the Space
          git push --force space main
